baseURL = 'http://budapest.ink/'
languageCode = 'en-us'
title = 'Budapest events and services'
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
theme = "hugo-winston-theme"
DefaultContentLanguage = "hu"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# config.toml
[params]
  google_analytics_id = "G-J388SJHVC1"
  twitter_handle = "@AndriiShylenko"
  showAuthorOnHomepage = false
  showAuthorOnPosts = false
  showIntroContentOnHomepage = true
  showPostsOnHomepage = true
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 2  # only used if usePaginationOnHomepage is false
  sortPostsByDateOldestFirst = false
  addDot = true
  addFrame = true
  highlightColor = '#7b16ff'
  baseColor = "#ffffff"
  baseOffsetColor = "#eaeaea"
  headingColor = "#1c1b1d"
  textColor = "#4e5157"
  dotColor = "#7b16ff"
  enableGoogleFonts = true 
  googleFontsUrl = "https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap"
  fontFamilyHeading = "Poppins"
  fontFamilyParagraph = "Helvetica"
  fontFamilyMonospace = "monospace"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = "Events"
    identifier = "blog"
    weight = 2
    url = "/posts/"
  [[menu.language]]
    name = "Events"
    identifier = "blog"
    weight = 2
    url = "/en/"
  [[menu.language]]
    name = "Events"
    identifier = "blog"
    weight = 2
    url = "/hu/"
    
[languages]
  [languages.en]
    title = "Budapest events and services"
    description = ""
    languageName = "English"
    contentDir = "content/en"
    languageCode = "en-us"
  [languages.hu]
    title = "Budapesti rendezvények és szolgáltatások"
    description = ""
    languageName = "Magyarul"
    contentDir = "content/hu"
    languageCode = "hu"
  
